version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "generalInvoiceParser"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-106au7cn3zwxv"
s3_prefix = "generalInvoiceParser"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EmailPrefix=\"Received\" PDFPrefix=\"PDF\" NSSecrets=\"{{resolve:ssm:/winward-invoice-pdf-to-csv-upload-to-ns/key-secrets:1}}\" NSFileCabinetIdPDFUploadFolder=\"12450\" NSFileCabinetIdCSVUploadFolder=\"12449\" NSSandboxProductionMode=\"PRODUCTION\""
confirm_changeset = true
