version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ap-inbox-production"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-106au7cn3zwxv"
s3_prefix = "ap-inbox-production"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
